#!/bin/bash
set -e

INPUT=$(cat)
FILE_PATH=$(printf '%s' "$INPUT" | jq -r '.tool_response.file_path // .tool_input.file_path // empty')

[ -z "$FILE_PATH" ] && exit 0

# Path-based skips: meta files, JSON, project-internal docs.
case "$FILE_PATH" in
  */.claude/*) exit 0 ;;
  */CLAUDE.md) exit 0 ;;
  */work-in-progress.html) exit 0 ;;
  *.json|*.lock|*.lockb) exit 0 ;;
  *.tsbuildinfo) exit 0 ;;
esac

# Generated-file path globs: never add a header to anything matching these
# (they're regenerated by tooling and the header would be wiped on next regen).
case "$FILE_PATH" in
  */database.ts|*/database.js) exit 0 ;;
  */types_db.ts|*/types_db.js) exit 0 ;;
  */*.generated.*) exit 0 ;;
  */generated/*) exit 0 ;;
  */__generated__/*) exit 0 ;;
  */node_modules/*|*/dist/*|*/build/*|*/out/*) exit 0 ;;
esac

[ -s "$FILE_PATH" ] || exit 0

# Generated-file content sniff: first 200 bytes contain a known marker.
if head -c 200 "$FILE_PATH" 2>/dev/null | grep -qiE '@generated|DO NOT EDIT|auto-generated|THIS FILE IS GENERATED|automatically generated|by the protocol buffer compiler'; then
  exit 0
fi

# Convention-aware framework skip: files whose role is unambiguous from
# framework convention (path + filename = full meaning). A header would
# add no information beyond the path.
PROJECT_DIR="${CLAUDE_PROJECT_DIR:-$PWD}"
BASENAME=$(basename "$FILE_PATH")

framework=""
if [ -f "$PROJECT_DIR/package.json" ]; then
  pkg="$PROJECT_DIR/package.json"
  if   grep -q '"next"'           "$pkg" 2>/dev/null; then framework="next"
  elif grep -q '"nuxt"'           "$pkg" 2>/dev/null; then framework="nuxt"
  elif grep -q '"@sveltejs/kit"'  "$pkg" 2>/dev/null; then framework="sveltekit"
  elif grep -q '"@remix-run'      "$pkg" 2>/dev/null; then framework="remix"
  elif grep -q '"astro"'          "$pkg" 2>/dev/null; then framework="astro"
  fi
fi

case "$framework" in
  next)
    case "$BASENAME" in
      page.tsx|page.jsx|page.ts|page.js) exit 0 ;;
      route.ts|route.js) exit 0 ;;
      layout.tsx|layout.jsx|layout.ts|layout.js) exit 0 ;;
      loading.tsx|loading.jsx|loading.ts|loading.js) exit 0 ;;
      error.tsx|error.jsx|error.ts|error.js) exit 0 ;;
      not-found.tsx|not-found.jsx|not-found.ts|not-found.js) exit 0 ;;
      default.tsx|default.jsx|default.ts|default.js) exit 0 ;;
      template.tsx|template.jsx|template.ts|template.js) exit 0 ;;
      middleware.ts|middleware.js) exit 0 ;;
      instrumentation.ts|instrumentation.js) exit 0 ;;
    esac
    ;;
  nuxt)
    case "$BASENAME" in
      app.vue|nuxt.config.ts|nuxt.config.js) exit 0 ;;
    esac
    ;;
  sveltekit)
    case "$BASENAME" in
      +page.svelte|+page.ts|+page.js|+page.server.ts|+page.server.js) exit 0 ;;
      +layout.svelte|+layout.ts|+layout.js|+layout.server.ts|+layout.server.js) exit 0 ;;
      +server.ts|+server.js|+error.svelte) exit 0 ;;
    esac
    ;;
  remix)
    case "$BASENAME" in
      root.tsx|root.jsx|entry.client.tsx|entry.client.jsx|entry.server.tsx|entry.server.jsx) exit 0 ;;
    esac
    ;;
  astro)
    case "$BASENAME" in
      *.astro)
        case "$FILE_PATH" in
          */pages/*) exit 0 ;;
          */layouts/*) exit 0 ;;
        esac
        ;;
    esac
    ;;
esac

jq -n --arg path "$FILE_PATH" '{
  hookSpecificOutput: {
    hookEventName: "PostToolUse",
    additionalContext: ("A Write tool call just created " + $path + ". If this file does not already begin on LINE 1 with a comment explaining WHY it exists (its purpose and role in the system), add one now. REQUIREMENTS: (1) The comment MUST start on line 1 — the very first character of the file. (2) Nothing may come before it: no blank line, no `<!doctype html>`, no `#!/...` shebang, no `<?xml ...?>` declaration, no `package` line, no `using`/`import`, nothing. If such a line currently sits on line 1, move it below the new comment. (3) Use the comment syntax appropriate to the file type (`<!-- -->` for HTML/XML, `#` for shell/Python/Ruby/YAML, `//` or `/* */` for C-family, `--` for SQL/Lua, etc.). (4) Keep it to 1-3 short lines. This header is intended for future Claude Code sessions reading the file.")
  }
}'
